[package]
name = "raw-memory-reader"
version = "0.1.0"
edition = "2021"
description = "Rust helper crate for reading raw bytes of memory of data."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
